# Generated by Django 5.2 on 2026-02-13 00:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_remove_materia_codigo_curso_capacidad_maxima_and_more'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActaInstitucional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consecutivo', models.IntegerField()),
                ('fecha', models.DateField()),
                ('hora_fin', models.TimeField()),
                ('titulo', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('COMITE', 'Comité de Convivencia'), ('CONSEJO', 'Consejo Académico'), ('SITUACION_ESPECIAL', 'Situación Especial')], max_length=50)),
                ('orden_dia', models.TextField()),
                ('contenido', models.TextField()),
                ('compromisos', models.TextField()),
                ('asistentes_externos', models.TextField(blank=True)),
                ('creador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wellbeing_actas_creadas', to=settings.AUTH_USER_MODEL)),
                ('implicado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wellbeing_actas_implicado', to=settings.AUTH_USER_MODEL)),
                ('participantes', models.ManyToManyField(related_name='wellbeing_actas_participantes', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='tenancy.tenant', verbose_name='Institución')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('ASISTIO', 'Asistió'), ('FALLA', 'Falla Injustificada'), ('EXCUSA', 'Falla Justificada'), ('TARDE', 'Llegada Tarde')], default='ASISTIO', max_length=20)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.curso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wellbeing_asistencias', to=settings.AUTH_USER_MODEL)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.materia')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wellbeing_asistencias_tomadas', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='tenancy.tenant', verbose_name='Institución')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Convivencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=3)),
                ('comentario', models.TextField(blank=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.curso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wellbeing_convivencias', to=settings.AUTH_USER_MODEL)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.periodo')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wellbeing_convivencias_registradas', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='tenancy.tenant', verbose_name='Institución')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('archivo_pei', models.FileField(blank=True, null=True, upload_to='institucion/docs/')),
                ('archivo_manual_convivencia', models.FileField(blank=True, null=True, upload_to='institucion/docs/')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='tenancy.tenant', verbose_name='Institución')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Observacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CONVIVENCIA', 'Convivencia'), ('ACADEMICA', 'Académica'), ('PSICOLOGICA', 'Psicológica')], default='CONVIVENCIA', max_length=20)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wellbeing_observaciones_autor', to=settings.AUTH_USER_MODEL)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wellbeing_observaciones', to=settings.AUTH_USER_MODEL)),
                ('periodo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.periodo')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='tenancy.tenant', verbose_name='Institución')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ObservadorArchivado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiante_nombre', models.CharField(max_length=255)),
                ('estudiante_username', models.CharField(max_length=150)),
                ('anio_lectivo_archivado', models.CharField(max_length=20)),
                ('archivo_pdf', models.FileField(upload_to='archivados/observadores/')),
                ('fecha_archivado', models.DateTimeField(auto_now_add=True)),
                ('eliminado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wellbeing_obs_eliminados', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='tenancy.tenant', verbose_name='Institución')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('observaciones_adicionales', models.TextField(blank=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wellbeing_seguimientos', to=settings.AUTH_USER_MODEL)),
                ('profesional', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wellbeing_seguimientos_profesional', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='tenancy.tenant', verbose_name='Institución')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
