# Generated by Django 5.2 on 2026-02-12 23:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='codigo',
        ),
        migrations.AddField(
            model_name='curso',
            name='capacidad_maxima',
            field=models.IntegerField(default=40),
        ),
        migrations.AddField(
            model_name='curso',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academics_cursos_dirigidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='curso',
            name='nombre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='curso',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='tenancy.tenant', verbose_name='Institución'),
        ),
        migrations.AddField(
            model_name='materia',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='academics.curso'),
        ),
        migrations.AddField(
            model_name='materia',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='tenancy.tenant', verbose_name='Institución'),
        ),
        migrations.AddField(
            model_name='periodo',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='tenancy.tenant', verbose_name='Institución'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='anio_escolar',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='curso',
            name='grado',
            field=models.CharField(choices=[('PREKINDER', 'Pre-Kínder'), ('KINDER', 'Kínder'), ('JARDIN', 'Jardín'), ('TRANSICION', 'Transición'), ('1', 'Primero'), ('2', 'Segundo'), ('3', 'Tercero'), ('4', 'Cuarto'), ('5', 'Quinto'), ('6', 'Sexto'), ('7', 'Séptimo'), ('8', 'Octavo'), ('9', 'Noveno'), ('10', 'Décimo'), ('11', 'Once')], max_length=20),
        ),
        migrations.CreateModel(
            name='AsignacionMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.curso')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academics_asignaciones', to=settings.AUTH_USER_MODEL)),
                ('materia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='academics.materia')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='tenancy.tenant', verbose_name='Institución')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BoletinArchivado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estudiante', models.CharField(max_length=255)),
                ('username_estudiante', models.CharField(max_length=150)),
                ('grado_archivado', models.CharField(max_length=50)),
                ('seccion_archivada', models.CharField(max_length=10)),
                ('anio_lectivo_archivado', models.CharField(max_length=20)),
                ('fecha_eliminado', models.DateTimeField(auto_now_add=True)),
                ('archivo_pdf', models.FileField(upload_to='boletines_archivados/')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academics_boletines_historial', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='tenancy.tenant', verbose_name='Institución')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DefinicionNota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('orden', models.IntegerField(default=1)),
                ('temas', models.TextField(blank=True)),
                ('materia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.materia')),
                ('periodo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.periodo')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='tenancy.tenant', verbose_name='Institución')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio_escolar', models.CharField(max_length=20)),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('puede_generar_boletin', models.BooleanField(default=True)),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matriculados', to='academics.curso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academics_matriculas', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='tenancy.tenant', verbose_name='Institución')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=3)),
                ('numero_nota', models.IntegerField(default=5)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academics_notas_estudiante', to=settings.AUTH_USER_MODEL)),
                ('materia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.materia')),
                ('periodo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.periodo')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academics_notas_registradas', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='tenancy.tenant', verbose_name='Institución')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NotaDetallada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=3)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('definicion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.definicionnota')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academics_detalles_notas', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='tenancy.tenant', verbose_name='Institución')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
